// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzsvkxxqckdeuwnwcjmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6c3ZreHhxY2tkZXV3bndjam1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MjI0NjYsImV4cCI6MjA4NjQ5ODQ2Nn0.4C2nCljSuF78zYHeOb6ba9sM141mtPMrAErOyM3Bi5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
